// Character Definitions for IDM Tournament Platform
// 60 characters total: 30 male + 30 female

export interface CharacterDef {
  name: string;
  slug: string;
  gender: 'male' | 'female';
  universe: string;
  alignment: string;
  classType: string;
  colors: { primary: string; secondary: string; accent: string };
}

export const CHARACTER_DEFINITIONS: CharacterDef[] = [
  // ═══════════════════════════════════════════
  // MALE CHARACTERS (30)
  // ═══════════════════════════════════════════
  {
    name: 'Shadow Blade',
    slug: 'shadow-blade',
    gender: 'male',
    universe: 'Dark Realm',
    alignment: 'Neutral',
    classType: 'Assassin',
    colors: { primary: '#1a1a2e', secondary: '#16213e', accent: '#e94560' },
  },
  {
    name: 'Iron Vanguard',
    slug: 'iron-vanguard',
    gender: 'male',
    universe: 'Steel Fortress',
    alignment: 'Lawful',
    classType: 'Tank',
    colors: { primary: '#4a4a4a', secondary: '#8a8a8a', accent: '#c0c0c0' },
  },
  {
    name: 'Pyro Knight',
    slug: 'pyro-knight',
    gender: 'male',
    universe: 'Inferno Kingdom',
    alignment: 'Good',
    classType: 'Warrior',
    colors: { primary: '#ff4500', secondary: '#ff6347', accent: '#ffd700' },
  },
  {
    name: 'Frost Mage',
    slug: 'frost-mage',
    gender: 'male',
    universe: 'Arctic Wastes',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#00bfff', secondary: '#87ceeb', accent: '#e0ffff' },
  },
  {
    name: 'Thunder God',
    slug: 'thunder-god',
    gender: 'male',
    universe: 'Celestial Palace',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#483d8b', secondary: '#6a5acd', accent: '#ffd700' },
  },
  {
    name: 'Dark Archer',
    slug: 'dark-archer',
    gender: 'male',
    universe: 'Shadow Forest',
    alignment: 'Chaotic',
    classType: 'Archer',
    colors: { primary: '#2d2d2d', secondary: '#4a3728', accent: '#8b0000' },
  },
  {
    name: 'Holy Paladin',
    slug: 'holy-paladin',
    gender: 'male',
    universe: 'Sacred Realm',
    alignment: 'Lawful',
    classType: 'Tank',
    colors: { primary: '#ffd700', secondary: '#fff8dc', accent: '#ffffff' },
  },
  {
    name: 'Storm Ranger',
    slug: 'storm-ranger',
    gender: 'male',
    universe: 'Wild Highlands',
    alignment: 'Good',
    classType: 'Archer',
    colors: { primary: '#228b22', secondary: '#32cd32', accent: '#90ee90' },
  },
  {
    name: 'Blood Hunter',
    slug: 'blood-hunter',
    gender: 'male',
    universe: 'Crimson Abyss',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#8b0000', secondary: '#dc143c', accent: '#ff6347' },
  },
  {
    name: 'Arcane Scholar',
    slug: 'arcane-scholar',
    gender: 'male',
    universe: 'Mystic Academy',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#4b0082', secondary: '#8a2be2', accent: '#dda0dd' },
  },
  {
    name: 'Steel Berserker',
    slug: 'steel-berserker',
    gender: 'male',
    universe: 'Iron Wastes',
    alignment: 'Chaotic',
    classType: 'Warrior',
    colors: { primary: '#708090', secondary: '#a9a9a9', accent: '#cd853f' },
  },
  {
    name: 'Wind Monk',
    slug: 'wind-monk',
    gender: 'male',
    universe: 'Cloud Temple',
    alignment: 'Good',
    classType: 'Warrior',
    colors: { primary: '#f5f5f5', secondary: '#dcdcdc', accent: '#00ced1' },
  },
  {
    name: 'Phantom Rogue',
    slug: 'phantom-rogue',
    gender: 'male',
    universe: 'Ghost Realm',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#191970', secondary: '#483d8b', accent: '#7b68ee' },
  },
  {
    name: 'Flame Sorcerer',
    slug: 'flame-sorcerer',
    gender: 'male',
    universe: 'Volcanic Isles',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#ff8c00', secondary: '#ff4500', accent: '#ffff00' },
  },
  {
    name: 'Earth Guardian',
    slug: 'earth-guardian',
    gender: 'male',
    universe: 'Stone Mountains',
    alignment: 'Lawful',
    classType: 'Tank',
    colors: { primary: '#8b4513', secondary: '#a0522d', accent: '#deb887' },
  },
  {
    name: 'Void Walker',
    slug: 'void-walker',
    gender: 'male',
    universe: 'Dimensional Rift',
    alignment: 'Neutral',
    classType: 'Assassin',
    colors: { primary: '#0d0d0d', secondary: '#1a1a1a', accent: '#9400d3' },
  },
  {
    name: 'Radiant Knight',
    slug: 'radiant-knight',
    gender: 'male',
    universe: 'Sun Kingdom',
    alignment: 'Lawful',
    classType: 'Warrior',
    colors: { primary: '#ffa500', secondary: '#ffd700', accent: '#ffffff' },
  },
  {
    name: 'Venom Striker',
    slug: 'venom-striker',
    gender: 'male',
    universe: 'Toxic Swamp',
    alignment: 'Chaotic',
    classType: 'Archer',
    colors: { primary: '#006400', secondary: '#32cd32', accent: '#adff2f' },
  },
  {
    name: 'Crystal Sage',
    slug: 'crystal-sage',
    gender: 'male',
    universe: 'Gem Caverns',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#00ced1', secondary: '#40e0d0', accent: '#e0ffff' },
  },
  {
    name: 'War Drummer',
    slug: 'war-drummer',
    gender: 'male',
    universe: 'Battle Arena',
    alignment: 'Neutral',
    classType: 'Warrior',
    colors: { primary: '#8b0000', secondary: '#b22222', accent: '#cd5c5c' },
  },
  {
    name: 'Night Stalker',
    slug: 'night-stalker',
    gender: 'male',
    universe: 'Dark Forest',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#0a0a0a', secondary: '#2f4f4f', accent: '#556b2f' },
  },
  {
    name: 'Dragon Rider',
    slug: 'dragon-rider',
    gender: 'male',
    universe: 'Sky Citadel',
    alignment: 'Good',
    classType: 'Warrior',
    colors: { primary: '#b22222', secondary: '#cd5c5c', accent: '#ffd700' },
  },
  {
    name: 'Rune Forger',
    slug: 'rune-forger',
    gender: 'male',
    universe: 'Ancient Forge',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#4682b4', secondary: '#5f9ea0', accent: '#b0c4de' },
  },
  {
    name: 'Silver Arrow',
    slug: 'silver-arrow',
    gender: 'male',
    universe: 'Moonlit Plains',
    alignment: 'Good',
    classType: 'Archer',
    colors: { primary: '#c0c0c0', secondary: '#d3d3d3', accent: '#f0f8ff' },
  },
  {
    name: 'Doom Bringer',
    slug: 'doom-bringer',
    gender: 'male',
    universe: 'Underworld',
    alignment: 'Chaotic',
    classType: 'Tank',
    colors: { primary: '#1c1c1c', secondary: '#3d0c02', accent: '#ff4500' },
  },
  {
    name: 'Nature Warden',
    slug: 'nature-warden',
    gender: 'male',
    universe: 'Enchanted Grove',
    alignment: 'Good',
    classType: 'Tank',
    colors: { primary: '#2e8b57', secondary: '#3cb371', accent: '#98fb98' },
  },
  {
    name: 'Crimson Blade',
    slug: 'crimson-blade',
    gender: 'male',
    universe: 'Blood Kingdom',
    alignment: 'Neutral',
    classType: 'Warrior',
    colors: { primary: '#dc143c', secondary: '#ff1493', accent: '#ffffff' },
  },
  {
    name: 'Mystic Ninja',
    slug: 'mystic-ninja',
    gender: 'male',
    universe: 'Hidden Village',
    alignment: 'Neutral',
    classType: 'Assassin',
    colors: { primary: '#2f2f2f', secondary: '#555555', accent: '#ff0000' },
  },
  {
    name: 'Tide Caller',
    slug: 'tide-caller',
    gender: 'male',
    universe: 'Ocean Depths',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#000080', secondary: '#4169e1', accent: '#00bfff' },
  },
  {
    name: 'Beast Tamer',
    slug: 'beast-tamer',
    gender: 'male',
    universe: 'Wild Frontier',
    alignment: 'Neutral',
    classType: 'Warrior',
    colors: { primary: '#8b4513', secondary: '#d2691e', accent: '#f4a460' },
  },

  // ═══════════════════════════════════════════
  // FEMALE CHARACTERS (30)
  // ═══════════════════════════════════════════
  {
    name: 'Luna Witch',
    slug: 'luna-witch',
    gender: 'female',
    universe: 'Moonlit Realm',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#191970', secondary: '#4169e1', accent: '#e6e6fa' },
  },
  {
    name: 'Rose Knight',
    slug: 'rose-knight',
    gender: 'female',
    universe: 'Garden Kingdom',
    alignment: 'Lawful',
    classType: 'Warrior',
    colors: { primary: '#ff69b4', secondary: '#ffb6c1', accent: '#ffffff' },
  },
  {
    name: 'Shadow Dancer',
    slug: 'shadow-dancer',
    gender: 'female',
    universe: 'Twilight Realm',
    alignment: 'Neutral',
    classType: 'Assassin',
    colors: { primary: '#2c003e', secondary: '#512b58', accent: '#957dad' },
  },
  {
    name: 'Storm Priestess',
    slug: 'storm-priestess',
    gender: 'female',
    universe: 'Temple of Storms',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#6a0dad', secondary: '#9370db', accent: '#dda0dd' },
  },
  {
    name: 'Frost Queen',
    slug: 'frost-queen',
    gender: 'female',
    universe: 'Frozen Throne',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#b0e0e6', secondary: '#add8e6', accent: '#ffffff' },
  },
  {
    name: 'Blood Priestess',
    slug: 'blood-priestess',
    gender: 'female',
    universe: 'Crimson Temple',
    alignment: 'Chaotic',
    classType: 'Mage',
    colors: { primary: '#8b0000', secondary: '#c71585', accent: '#ff69b4' },
  },
  {
    name: 'Star Archer',
    slug: 'star-archer',
    gender: 'female',
    universe: 'Celestial Realm',
    alignment: 'Good',
    classType: 'Archer',
    colors: { primary: '#4b0082', secondary: '#800080', accent: '#ffd700' },
  },
  {
    name: 'Iron Maiden',
    slug: 'iron-maiden',
    gender: 'female',
    universe: 'Steel Empire',
    alignment: 'Lawful',
    classType: 'Tank',
    colors: { primary: '#696969', secondary: '#a9a9a9', accent: '#ff69b4' },
  },
  {
    name: 'Forest Huntress',
    slug: 'forest-huntress',
    gender: 'female',
    universe: 'Emerald Woods',
    alignment: 'Good',
    classType: 'Archer',
    colors: { primary: '#228b22', secondary: '#90ee90', accent: '#f0fff0' },
  },
  {
    name: 'Dark Sorceress',
    slug: 'dark-sorceress',
    gender: 'female',
    universe: 'Abyssal Tower',
    alignment: 'Chaotic',
    classType: 'Mage',
    colors: { primary: '#1a0a2e', secondary: '#3d1e6d', accent: '#9b59b6' },
  },
  {
    name: 'Valkyrie',
    slug: 'valkyrie',
    gender: 'female',
    universe: 'Asgard',
    alignment: 'Lawful',
    classType: 'Warrior',
    colors: { primary: '#daa520', secondary: '#ffd700', accent: '#ffffff' },
  },
  {
    name: 'Wind Dancer',
    slug: 'wind-dancer',
    gender: 'female',
    universe: 'Sky Sanctum',
    alignment: 'Good',
    classType: 'Assassin',
    colors: { primary: '#87ceeb', secondary: '#b0e0e6', accent: '#f0f8ff' },
  },
  {
    name: 'Poison Ivy',
    slug: 'poison-ivy',
    gender: 'female',
    universe: 'Toxic Garden',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#006400', secondary: '#9acd32', accent: '#adff2f' },
  },
  {
    name: 'Crystal Empress',
    slug: 'crystal-empress',
    gender: 'female',
    universe: 'Diamond Palace',
    alignment: 'Lawful',
    classType: 'Tank',
    colors: { primary: '#e0ffff', secondary: '#afeeee', accent: '#b0c4de' },
  },
  {
    name: 'Blaze Witch',
    slug: 'blaze-witch',
    gender: 'female',
    universe: 'Volcanic Peak',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#ff4500', secondary: '#ff6347', accent: '#ffa07a' },
  },
  {
    name: 'Nightshade',
    slug: 'nightshade',
    gender: 'female',
    universe: 'Dark Garden',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#1a1a2e', secondary: '#2d2d44', accent: '#7b2d8e' },
  },
  {
    name: 'Sun Priestess',
    slug: 'sun-priestess',
    gender: 'female',
    universe: 'Solar Temple',
    alignment: 'Good',
    classType: 'Mage',
    colors: { primary: '#ffa500', secondary: '#ffd700', accent: '#ffffe0' },
  },
  {
    name: 'War Maiden',
    slug: 'war-maiden',
    gender: 'female',
    universe: 'Battle Plains',
    alignment: 'Neutral',
    classType: 'Warrior',
    colors: { primary: '#8b4513', secondary: '#cd853f', accent: '#deb887' },
  },
  {
    name: 'Ocean Siren',
    slug: 'ocean-siren',
    gender: 'female',
    universe: 'Deep Ocean',
    alignment: 'Neutral',
    classType: 'Mage',
    colors: { primary: '#006994', secondary: '#40e0d0', accent: '#afeeee' },
  },
  {
    name: 'Soul Reaper',
    slug: 'soul-reaper',
    gender: 'female',
    universe: 'Spirit World',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#2f2f2f', secondary: '#808080', accent: '#00ffff' },
  },
  {
    name: 'Thunder Maiden',
    slug: 'thunder-maiden',
    gender: 'female',
    universe: 'Storm Peaks',
    alignment: 'Good',
    classType: 'Warrior',
    colors: { primary: '#483d8b', secondary: '#7b68ee', accent: '#e6e6fa' },
  },
  {
    name: 'Jade Assassin',
    slug: 'jade-assassin',
    gender: 'female',
    universe: 'Eastern Empire',
    alignment: 'Neutral',
    classType: 'Assassin',
    colors: { primary: '#00a86b', secondary: '#2e8b57', accent: '#98fb98' },
  },
  {
    name: 'Holy Archer',
    slug: 'holy-archer',
    gender: 'female',
    universe: 'Divine Realm',
    alignment: 'Lawful',
    classType: 'Archer',
    colors: { primary: '#ffd700', secondary: '#fff8dc', accent: '#fffacd' },
  },
  {
    name: 'Lava Queen',
    slug: 'lava-queen',
    gender: 'female',
    universe: 'Magma Core',
    alignment: 'Chaotic',
    classType: 'Mage',
    colors: { primary: '#cc3300', secondary: '#ff4500', accent: '#ff6347' },
  },
  {
    name: 'Mystic Healer',
    slug: 'mystic-healer',
    gender: 'female',
    universe: 'Sacred Garden',
    alignment: 'Good',
    classType: 'Tank',
    colors: { primary: '#90ee90', secondary: '#98fb98', accent: '#f0fff0' },
  },
  {
    name: 'Shadow Weaver',
    slug: 'shadow-weaver',
    gender: 'female',
    universe: 'Void Realm',
    alignment: 'Chaotic',
    classType: 'Assassin',
    colors: { primary: '#0d0d2b', secondary: '#1a1a4e', accent: '#663399' },
  },
  {
    name: 'Golden Valkyrie',
    slug: 'golden-valkyrie',
    gender: 'female',
    universe: 'Asgard',
    alignment: 'Lawful',
    classType: 'Warrior',
    colors: { primary: '#daa520', secondary: '#b8860b', accent: '#ffd700' },
  },
  {
    name: 'Ice Dancer',
    slug: 'ice-dancer',
    gender: 'female',
    universe: 'Glacier Realm',
    alignment: 'Good',
    classType: 'Archer',
    colors: { primary: '#add8e6', secondary: '#e0ffff', accent: '#f0f8ff' },
  },
  {
    name: 'Chaos Witch',
    slug: 'chaos-witch',
    gender: 'female',
    universe: 'Dimensional Rift',
    alignment: 'Chaotic',
    classType: 'Mage',
    colors: { primary: '#4b0082', secondary: '#ff00ff', accent: '#ff1493' },
  },
];
